# wrangler.toml
name = "gemini-liyanche"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "aa59933c7cc14b92aa6f72fc4058998d"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "d33ef0f9c9114abbad0b0c6ce257746c"
